version: '2'

volumes:
    logs:
        driver: local

services:
    db:
        container_name: mysql
        build:
            context: .
            dockerfile: DB_Dockerfile
        restart: always
        ports:
            - "3306:3306"
        environment:
          MYSQL_ROOT_PASSWORD: password

    slim: 
        build:
            context: .
            dockerfile: Dockerfile
        working_dir: /var/www
        command: php -S 0.0.0.0:8080 -t public index.php
        environment:
            docker: "true"
        ports:
            - 8080:8080
        volumes:
            - .:/var/www
            - logs:/var/www/logs
        links:
            - db
